config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'products#index'

  resources :products do
  end
  resources :user_reviews
  put 'products/:id/scrape_amazon', to: 'products#scrape_amazon', as: 'product_scrape_amazon'
  put 'products/:id/scrape_engadget', to: 'products#scrape_engadget', as: 'product_scrape_engadget'

  resources :critic_reviews

  get 'products_recommend', to: 'products#recommend', as: 'product_recommend'
    post 'likes/create_like', to: 'likes#create_like'
    post 'likes/create_possession', to: 'likes#create_possession'
    post 'likes/create_dislike', to: 'likes#create_dislike'

end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  before_action :set_user_review, only: [:show, :edit, :update, :destroy]

  # GET /user_reviews
  # GET /user_reviews.json
  def index
    @user_reviews = UserReview.all
  end

  # GET /user_reviews/1
  # GET /user_reviews/1.json
  def show
  end

  # GET /user_reviews/new
  def new
    @user_review = UserReview.new
  end

  # GET /user_reviews/1/edit
  def edit
  end

  # POST /user_reviews
  # POST /user_reviews.json
  def create
    attrs = user_review_params.merge(:user_id => current_user.id)
    attrs[:product_id] = attrs[:product_id].to_i
    @user_review = UserReview.new(attrs)

    respond_to do |format|
      if @user_review.save
        format.html { redirect_to @user_review, notice: 'User review was successfully created.' }
        format.json { render :show, status: :created, location: @user_review }
      else
        format.html { render :new }
        format.json { render json: @user_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_reviews/1
  # PATCH/PUT /user_reviews/1.json
  def update
    respond_to do |format|
      if @user_review.update(user_review_params)
        format.html { redirect_to @user_review, notice: 'User review was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_review }
      else
        format.html { render :edit }
        format.json { render json: @user_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_reviews/1
  # DELETE /user_reviews/1.json
  def destroy
    @user_review.destroy
    respond_to do |format|
      format.html { redirect_to user_reviews_url, notice: 'User review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_review
      @user_review = UserReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_review_params
      params.require(:user_review).permit(:comment, :rating, :user_id, :product_id)
    end
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/views/user_reviews/_form.html.erb
<%= form_for(@user_review) do |f| %>
  <% if @user_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_review.errors.count, "error") %> prohibited this user_review from being saved:</h2>

      <ul>
      <% @user_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :product_id, :value => params[:product_id] %>
    <div class="control-group">
      <%= f.label :comment, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :comment, :class => 'form-control', :cols => '10', :rows => '10' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :rating, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :rating, 1..10 %>
      </div>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_reviews/edit.html.erb
<h1>Editing User Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_review %> |
<%= link_to 'Back', user_reviews_path %>

app/views/user_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_reviews.each do |user_review| %>
      <tr>
        <td><%= link_to 'Show', user_review %></td>
        <td><%= link_to 'Edit', edit_user_review_path(user_review) %></td>
        <td><%= link_to 'Destroy', user_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User review', new_user_review_path %>

app/views/user_reviews/new.html.erb
<h1>New User Review</h1>

<%= render 'form' %>

<%= link_to 'Back', user_reviews_path %>

app/views/user_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_review_path(@user_review) %> |
<%= link_to 'Back', products_path %>