config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'products#index'

  resources :products do
  end
  resources :user_reviews
  put 'products/:id/scrape_amazon', to: 'products#scrape_amazon', as: 'product_scrape_amazon'
  put 'products/:id/scrape_engadget', to: 'products#scrape_engadget', as: 'product_scrape_engadget'

  resources :critic_reviews

  get 'products_recommend', to: 'products#recommend', as: 'product_recommend'
    post 'likes/create_like', to: 'likes#create_like'
    post 'likes/create_possession', to: 'likes#create_possession'
    post 'likes/create_dislike', to: 'likes#create_dislike'

end

app/controllers/critic_reviews_controller.rb
class CriticReviewsController < ApplicationController
  before_action :set_critic_review, only: [:show, :edit, :update, :destroy]

  # GET /critic_reviews
  # GET /critic_reviews.json
  def index
    @critic_reviews = CriticReview.all
  end

  # GET /critic_reviews/1
  # GET /critic_reviews/1.json
  def show
    @review = CriticReview.find(params[:id])
    @summary = params[:summary]
  end

  # GET /critic_reviews/new
  def new
    @critic_review = CriticReview.new
  end

  # GET /critic_reviews/1/edit
  def edit
  end

  # POST /critic_reviews
  # POST /critic_reviews.json
  def create
    @critic_review = CriticReview.new(critic_review_params)

    respond_to do |format|
      if @critic_review.save
        format.html { redirect_to @critic_review, notice: 'Critic review was successfully created.' }
        format.json { render :show, status: :created, location: @critic_review }
      else
        format.html { render :new }
        format.json { render json: @critic_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /critic_reviews/1
  # PATCH/PUT /critic_reviews/1.json
  def update
    respond_to do |format|
      if @critic_review.update(critic_review_params)
        format.html { redirect_to @critic_review, notice: 'Critic review was successfully updated.' }
        format.json { render :show, status: :ok, location: @critic_review }
      else
        format.html { render :edit }
        format.json { render json: @critic_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /critic_reviews/1
  # DELETE /critic_reviews/1.json
  def destroy
    @critic_review.destroy
    respond_to do |format|
      format.html { redirect_to critic_reviews_url, notice: 'Critic review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_critic_review
      @critic_review = CriticReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def critic_review_params
      params[:critic_review]
    end
end

app/helpers/critic_reviews_helper.rb
module CriticReviewsHelper
end

app/views/critic_reviews/_form.html.erb
<%= form_for(@critic_review) do |f| %>
  <% if @critic_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@critic_review.errors.count, "error") %> prohibited this critic_review from being saved:</h2>

      <ul>
      <% @critic_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/critic_reviews/edit.html.erb
<h1>Editing Critic Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @critic_review %> |
<%= link_to 'Back', critic_reviews_path %>

app/views/critic_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Critic Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @critic_reviews.each do |critic_review| %>
      <tr>
        <td><%= link_to 'Show', critic_review %></td>
        <td><%= link_to 'Edit', edit_critic_review_path(critic_review) %></td>
        <td><%= link_to 'Destroy', critic_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Critic review', new_critic_review_path %>

app/views/critic_reviews/new.html.erb
<h1>New Critic Review</h1>

<%= render 'form' %>

<%= link_to 'Back', critic_reviews_path %>

app/views/critic_reviews/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <link href=' http://fonts.googleapis.com/css?family=Sorts+Mill+Goudy&subset=all' rel='stylesheet' type='text/css'>
</head>
<body class='review-body'>
<div class='container'>
  <div class="settings row">
    <div class="image-settings col-md-2 col-md-offset-1">
      <input type="image" display-value='block' src="http://icons.iconarchive.com/icons/icons8/windows-8/128/City-No-Camera-icon.png">
    </div>
    <div class="align-settings col-md-2">
      <input type="image" align-value='justify' src="http://icons.iconarchive.com/icons/icons8/ios7/256/Editing-Align-Justify-icon.png">
      <input type="image" align-value='left' src="http://icons.iconarchive.com/icons/icons8/ios7/256/Editing-Align-Left-icon.png">
    </div>
    <div class="length-settings col-md-2">
      <input type="image" length-action='+' src="https://cdn4.iconfinder.com/data/icons/epic-outlines/30/enlarge_horizontal-128.png">
      <input type="image" length-action='-' src="https://cdn4.iconfinder.com/data/icons/epic-outlines/30/shrink_horizontal-256.png">
    </div>
    <div class="font-size-settings col-md-2">
      <input type="image" font-size-action="+" src="http://icons.iconarchive.com/icons/icons8/ios7/512/Arrows-Up-4-icon.png">
      <span class="glyphicon glyphicon-text-size" aria-hidden="true"></span>
      <input type="image" font-size-action="-" src="http://icons.iconarchive.com/icons/icons8/ios7/512/Arrows-Down-4-icon.png">
    </div>
    <div class="background-settings col-md-2">
      <div class="background-setting-white" bg-color-value="white" style="cursor: pointer;">a</div>
      <div class="background-setting-black" bg-color-value="black" style="cursor: pointer;">a</div>
      <div class="background-setting-lightyellow" bg-color-value="lightyellow" style="cursor: pointer;">a</div>
    </div>
  </div>

</div>
<div class="container article-container">
  <div class="article">
    <div class="article-title"><%= @review.title %>
    <% if @summary %>
          (Summary) <% end %></div>
    <div class="article-header">
      <div class="article-author"><%= "#{@review.author}" %></div>
      <div class="article-published"><%# " | #{@published.to_date.to_s(:rfc822)} " %></div>
      <div class="article-feed-title"><%# " | #{Feed.find(@article.feed_id).title}" %></div>
    </div>
    <div class="article-content">
      <% if @summary %>
          <%= @review.summary.try(:html_safe) %>
      <% else %>
          <%= @review.page_html.try(:html_safe) %>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>