config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'products#index'

  resources :products do
  end
  resources :user_reviews
  put 'products/:id/scrape_amazon', to: 'products#scrape_amazon', as: 'product_scrape_amazon'
  put 'products/:id/scrape_engadget', to: 'products#scrape_engadget', as: 'product_scrape_engadget'

  resources :critic_reviews

  get 'products_recommend', to: 'products#recommend', as: 'product_recommend'
    post 'likes/create_like', to: 'likes#create_like'
    post 'likes/create_possession', to: 'likes#create_possession'
    post 'likes/create_dislike', to: 'likes#create_dislike'

end

app/models/product.rb
require 'open-uri'

class Product < ActiveRecord::Base
  has_many :analytics_stats
  has_many :user_reviews
  has_many :critic_reviews
  has_many :likes
  has_many :dislikes
  has_many :possessions
  has_many :likers, through: :likes, source: :user
  has_many :dislikers, through: :dislikes, source: :user
  has_many :havers, through: :possessions, source: :user

  def self.search(string)
    sort = false
    new_string = string

    if new_string.blank?
      products = Product.all
    else
      if string.split(',')[-1].strip.start_with?('sort')
        sort = true
        order_param = string.split(',')[-1].strip
        last_index = string.rindex(',')
        if !last_index.nil?
          new_string = string[0..last_index]
        else
          new_string = ''
        end
        order = order_param.split('sort:')[1].strip
        s = order.split(' ', 2)
        hash = {s[1].downcase.tr(' ', '_').to_sym => s[0].to_sym}
      end
      if new_string.blank?
        products = Product.all
      else
        conditions = new_string.split(',').collect do |m|
          m.strip!
          delim = (m.include?('=') ? '=' : 'like')
          expr = m.split(/=|like/i)
          "#{expr[0].strip.downcase.tr(' ', '_')} #{delim} '#{expr[1].strip}'"
        end

        final_condition = conditions.join(' AND ')
        products = Product.where(final_condition)
      end
    end

    if sort
      return products.order(hash)
    else
      return products
    end
  end

  def get_details_from_amazon
    product_page_url = fetch_amazon_page_url(self.name)
    product_page_html = open(product_page_url, "User-Agent" => "Device Select").read
    @html_doc = Nokogiri::HTML(product_page_html)

    amazon_fields = {:camera => 'Webcam', :screen_size => 'Screen Size', :company => 'Brand Name', :memory => 'RAM', :processor => 'Processor', :battery => 'Average Battery Life (in hours)'}
    new_attrs = {}
    amazon_fields.keys.each do |f|
      attr = @html_doc.xpath("//div[@class='pdTab']/table/tbody/tr/td[contains(text(), '#{amazon_fields[f]}')]/following-sibling::td/text()").to_s
      puts attr
      unless attr.blank?
        new_attrs[f] = attr
      end
    end

    new_attrs[:img_url] = @html_doc.xpath("//li[contains(@class, 'itemNo0')]//img[contains(@id, 'landingImage')]/@src").to_s
    # agent = Mechanize.new
    # results_page = agent.get(product_page_url)
    price = @html_doc.xpath("//*[@id='priceblock_ourprice']").to_s
    if (price.blank?)
      price = @html_doc.xpath("//*[@id='olp_feature_div']/div/span[1]/span").to_s
    end
    price = price.delete "$,"
    price = price.to_i
    new_attrs[:price] = price
    self.update(new_attrs)
    # puts self.errors
    self.save!
  end

  def self.generate_readable_html(url)
    readability_url = "http://www.readability.com/m?url=#{CGI::escape(url)}"
    html_content = open(readability_url).read
    html_doc = Nokogiri::HTML(html_content)
    complete_content_html = html_doc.search('//article').first.to_html
    complete_content_html_doc = Nokogiri::HTML(complete_content_html)
    # header_html = html_doc.search('//header').first.to_html
    title = html_doc.search('//header')[1].css('h1[id=rdb-article-title]').text
    doc = Pismo::Document.new(url)
    author = doc.author
    published = doc.datetime

    content_html_doc = complete_content_html_doc.search('//section').first
    content_html_doc.search('//ul').each do |node|
      node.remove
    end

    original_html = Nokogiri::HTML(open(url).read)
    css_lines = original_html.css('link[href$=css]')

    final_html = '<html><head>'
    css_lines.each do |line|
      # final_html = final_html + line.to_html
    end
    return final_html + "</head><body>#{content_html_doc.to_html}</body></html>", title, author, published
  end

  # Returns array of sentences
  def self.generate_summary(html)
    html_doc = Nokogiri::HTML(html)
    paragraphs = []
    m = TactfulTokenizer::Model.new
    tokenizer = Tokenizer::Tokenizer.new
    html_doc.search('p').each do |p|
      paragraphs << m.tokenize_text(p.text) unless p.text.blank? || p.text.length <= 50 || p.text.downcase.include?('comments')
    end
    sentences = paragraphs.flatten
    sentence_pair_scores = Hash.new
    sentences.each do |s1|
      sentences.each do |s2|
        if s1 == s2
          sentence_pair_scores[[s1, s2]] = 0
        else
          sentence_pair_scores[[s1, s2]] = (tokenizer.tokenize(s1).select { |t| Stopwords.valid?(t) } & tokenizer.tokenize(s2).select { |t| Stopwords.valid?(t) }).count
        end
      end
    end
    sentence_scores = {}
    sentences.each do |s|
      sentence_scores[s] = 0
      sentences.each do |s2|
        sentence_scores[s] += sentence_pair_scores[[s, s2]]
      end
    end
    full_summary = paragraphs.collect { |p| sentence_scores.slice(*p).sort_by {|_, v| -v }.first[0] }
    # threshold = full_summary.sort_by {|sentence, score| -score}[5][1]
    # summary = sentence_scores.select { |s, score| s if score >= threshold}.keys
    # Ensure a sentence from first and last paragraphs
    # summary.unshift(full_summary.first[0]) if full_summary.first[1] < threshold
    # summary << full_summary.last[0] if full_summary.last[1] < threshold
    '<p>' + full_summary.join('</p><p>') + '</p>'
  end

  #Kausik's price methods
  def get_price_from_amazon
    product = Product.name
    amazon_url = fetch_amazon_page_url(product)
    agent = Mechanize.new
    results_page = agent.get(amazon_url)
    price = results_page.search("//*[@id='priceblock_ourprice']").text
    price = price.slice!(1..-1).to_i
  end

  # private
  def fetch_amazon_page_url(product)
    product_param = product.downcase.split(' ').join('+')
    agent = Mechanize.new
    results_page = agent.get("https://www.google.com/search?q=#{product_param}+amazon+%22*phone%22+OR+%22tablet%22+OR+%22laptop%22+site%3Aamazon.com")
    # page_html = open("http://www.amazon.com/s/field-keywords=#{product_param}", "User-Agent" => "Device Select").read
    results_page.links[24].href.split('/url?q=')[1].split('&sa')[0]
    ## Only for testing
    # product_page_html = open(product_page_url).read
    # @html_doc = Nokogiri::HTML(product_page_html)
    # screen_size = @html_doc.xpath("//td[text() = 'Brand Name']/following-sibling::td/text()").to_s

  end

  def self.fetch_engadget_page_url(product)
    product_param = product.downcase.split(' ').join('+')
    agent = Mechanize.new
    results_page = agent.get("https://www.google.com/search?q=#{product_param}+site%3Aengadget.com%2Fproducts")
    results_page.links[24].href.split('/url?q=')[1].split('&sa')[0]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :scrape_amazon, :scrape_engadget ]

  # GET /products
  # GET /products.json
  def index
    if params[:search]
      @products = Product.search(params[:search])
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def recommend
    other_users = User.all - [current_user]
    user_similarities = {}
    other_users.each do |u|
      if (current_user.liked_products | current_user.disliked_products | u.liked_products | u.disliked_products).count == 0
        user_similarities[u] = 0
      else
        user_similarities[u] = ((current_user.liked_products & u.liked_products).count +
            (current_user.disliked_products & u.disliked_products).count -
            (current_user.liked_products & u.disliked_products).count -
            (current_user.disliked_products & u.liked_products).count).to_f /
            (current_user.liked_products | current_user.disliked_products | u.liked_products | u.disliked_products).count
      end

    end

    product_like_probs = {}
    (Product.all - current_user.owned_products).each do |p|
      if p.likers.count + p.dislikers.count == 0
        product_like_probs[p] = 0
      else
        product_like_probs[p] = (user_similarities.slice(*p.likers).values.sum - user_similarities.slice(*p.dislikers).values.sum).to_f/(p.likers.count + p.dislikers.count)
      end
    end
    @recommendations = product_like_probs.sort_by { |k,v| -v }[0..2].collect { |a| a[0] }
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrape_amazon
    @product.get_details_from_amazon
    redirect_to :action => 'index'
  end

  def scrape_engadget
    @product.get_details_from_engadget
    redirect_to :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :company, :name, :screen_size, :memory, :processor, :battery, :camera, :img_url)
    end

end

app/helpers/products_helper.rb
require 'open-uri'
module ProductsHelper

end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

    <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
    <div class="control-group">
      <%= f.label :company, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :company, :class => 'form-control' %>
      </div>
    </div>
  <div class="control-group">
    <%= f.label :processor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :processor, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :screen_size, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :screen_size, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :memory, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :memory, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :camera, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :camera, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :battery, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :battery, :class => 'form-control' %>
    </div>
  </div>
    <div class="control-group">
      <%= f.label :price, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
    </div>
  <!--<div class="control-group">-->
    <!--<%# f.label :img_url, :class => 'control-label' %>-->
    <!--<div class="controls">-->
      <!--<%# f.text_field :img_url, :class => 'form-control' %>-->
    <!--</div>-->
    <!--<%# error_span(@product[:img_url]) %>-->
  <!--</div>-->


  <%= f.submit nil, :class => 'btn btn-primary new-button' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            products_path, :class => 'btn btn-default new-button' %>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%= link_to t('Logout'), destroy_user_session_path, :method => :delete %>

<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag(products_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Products" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i></button>
    </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:company) %></th>
      <th><%= model_class.human_attribute_name(:processor) %></th>
      <th><%= model_class.human_attribute_name(:screen_size) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:memory) %></th>
      <th><%= model_class.human_attribute_name(:camera) %></th>
      <th><%= model_class.human_attribute_name(:battery) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%# model_class.human_attribute_name(:img_url) %></th>
      <th><%# model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.company %></td>
        <td><%= product.processor %></td>
        <td><%= product.screen_size %></td>
        <td><%= product.name %></td>
        <td><%= product.memory %></td>
        <td><%= product.camera %></td>
        <td><%= product.battery %></td>
        <td><%= product.price %></td>
        <td><%# product.img_url %></td>
        <td><%#l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to image_tag("http://amazonpickingchallenge.org/amazon_logo.png", :class => 'amazon-pic', :border => 0, :size => '40x15'), product_scrape_amazon_path(product), :class => 'btn btn-default btn-xs', method: :put %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.recommend'), product_recommend_path, :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/recommend.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
<h1>Recommendations</h1>
<% @recommendations.each do |r| %>

    <div class="row">
      <div class="col-md-3">
        <dl class="dl-horizontal">
          <dt><strong>Company:</strong></dt>
          <dd><%= r.company %></dd>
          <dt><strong>Processor:</strong></dt>
          <dd><%= r.processor %></dd>
          <dt><strong>Screen Size:</strong></dt>
          <dd><%= r.screen_size %></dd>
          <dt><strong>Name:</strong></dt>
          <dd><%= r.name %></dd>
          <dt><strong>Memory:</strong></dt>
          <dd><%= r.memory %></dd>
          <dt><strong>Camera:</strong></dt>
          <dd><%= r.camera %></dd>
          <dt><strong>Battery:</strong></dt>
          <dd><%= r.battery %></dd>
          <dt><strong>Price:</strong></dt>
          <dd><%= r.price %></dd>
        </dl>
      </div>
      <div class="col-md-6">
        <% unless r.img_url.nil? %>
            <img src=<%= r.img_url %>>
        <% end %>
      </div>
    </div>
<% end %>
</body>
</html>

app/views/products/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%- model_class = Product -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row">
  <div class="col-md-3">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:company) %>:</strong></dt>
      <dd><%= @product.company %></dd>
      <dt><strong><%= model_class.human_attribute_name(:processor) %>:</strong></dt>
      <dd><%= @product.processor %></dd>
      <dt><strong><%= model_class.human_attribute_name(:screen_size) %>:</strong></dt>
      <dd><%= @product.screen_size %></dd>
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @product.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:memory) %>:</strong></dt>
      <dd><%= @product.memory %></dd>
      <dt><strong><%= model_class.human_attribute_name(:camera) %>:</strong></dt>
      <dd><%= @product.camera %></dd>
      <dt><strong><%= model_class.human_attribute_name(:battery) %>:</strong></dt>
      <dd><%= @product.battery %></dd>
      <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
      <dd><%= @product.price %></dd>
    </dl>
  </div>
  <div class="col-md-6">
    <% unless @product.img_url.nil? %>
        <img src=<%= @product.img_url %>>
    <% end %>
  </div>
</div>
<%= link_to t('.back', :default => t("helpers.links.back")),
            products_path, :class => 'btn btn-default' %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.Write a Review'), new_user_review_path(:product_id => @product.id), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            product_path(@product),
            :method => 'delete',
            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
            :class => 'btn btn-danger' %>

<%= render 'user_reviews/index', :reviews => @product.user_reviews.sort_by { |r| r.created_at }.reverse! %>

<div class="like-want-buttons" role="group">
  <br><div>
  <%= link_to t('.I have it!', 'button-value' => "have"), likes_create_possession_path(:product_id => @product.id, :user_id => current_user.id), :method => 'post', :class => 'btn btn-primary', :remote => true %>
  <span class = "label label-default"><%= @product.havers.count %></span>
  </div>
  <div>
    <h5>Contact Info for owners of this product</h5>
    <% @product.havers.each do |h| %>
    <%= h.email %>
        <% end %>
  </div>
  <%## @product.havers.count %>
  <br><div>
  <%= link_to t('.I like it!', 'button-value' => "like"), likes_create_like_path(:product_id => @product.id, :user_id => current_user.id), :method => 'post', :class => 'btn btn-primary', :remote => true %>
  <span class = "label label-default"><%= @product.likers.count %></span>
</div><br><div>
  <%= link_to t('.I dislike it!', 'button-value' => "dislike"), likes_create_dislike_path(:product_id => @product.id, :user_id => current_user.id), :method => 'post', :class => 'btn btn-primary', :remote => true %>
  <span class = "label label-default"><%= @product.dislikers.count %></span>
</div><br>

</div>

<div class="analytics">
  <h1>Analytics</h1>
  <%= line_chart(@product.analytics_stats.collect { |a| {a.date => a.like_count} }.inject(:merge), {library: {pointSize: 0, hAxis: {title: "Timeline"}, vAxis: {title: "Users that Like"}}}) %>
  <%= line_chart(@product.analytics_stats.collect { |a| {a.date => a.have_count} }.inject(:merge), {library: {pointSize: 0, hAxis: {title: "Timeline"}, vAxis: {title: "Users that have"}}}) %>
  <%= line_chart(@product.analytics_stats.collect { |a| {a.date => a.price} }.inject(:merge), {library: {pointSize: 0, hAxis: {title: "Timeline"}, vAxis: {title: "Price"}}}) %>
</div>
<div class="critic-reviews">
  <h1>Critic Reviews</h1>
  <% @product.critic_reviews.each do |r| %>
      <%= link_to r.title, critic_review_path(:id => r.id) %>: <%= link_to 'Summary', critic_review_path(:id => r.id, :summary => true) %><br>
  <% end %>
</div>